export interface UldProxPacket {
    id: string;
    pt: string;
    ts: number;
    glat?: number;
    glon?: number;
    bat: number;
    C: number;
    st: string;
    e0: number;
    G1?: string;
    G2?: string;
    hdp?: number;
    rssi0?: number;
    A0?: string;
    A1?: string;
    A2?: string;
    mmc?: number;
    mnc?: number;
    tac?: number;
    cti?: number;
    celltowers?: string;
    T0?: number;
    H0?: number;
    P0?: number;
    L0?: number;
    TP?: number;
    G3?: string;
    morepids?: string;
    VersionInfo?: string;
    G4?: string;
    G5?: string;
    G6?: string;
    [key: string]: string | number | undefined;
};